feat: add italian readme
hydralauncher/hydra pull request #1251
Opened 2024-11-23 15:18 UTC by dan098

**When submitting this pull request, I confirm the following (please check the boxes):**

- [x] I have read and understood the [Contributor Guidelines](https://github.com/hydralauncher/hydra?tab=readme-ov-file#ways-you-can-contribute).
- [x] I have checked that there are no duplicate pull requests related to this request.
- [x] I have considered, and confirm that this submission is valuable to others.
- [x] I accept that this submission may not be used and the pull request may be closed at the discretion of the maintainers.

**Fill in the PR content:**

-

2024-11-27 03:51 UTC, Hachi-R requested changes
please keep your version as close as possible to the main version

2024-11-27 03:51 UTC, Hachi-R commented on README.it.md
> +    <strong>Hydra è un game launcher con il proprio client bittorrent e autogestore di repacks.</strong>
> e autogestore di repacks

this part was not in the original readme, please keep only what already exists

2024-11-27 03:51 UTC, Hachi-R commented on README.it.md
> +[<img src="./resources/icon.png" width="144"/>](https://hydralauncher.site)
please, change to the correct path

2024-11-27 03:51 UTC, Hachi-R commented on README.it.md
> +![Hydra Catalogue](./docs/screenshot.png)
please, change to the correct path

2024-11-27 03:51 UTC, Hachi-R commented on README.it.md
> +[![be](https://img.shields.io/badge/lang-be-orange)](README.be.md)
add the missing languages

2024-11-27 03:51 UTC, Hachi-R commented on README.it.md
> +**Hydra** è un **Game Launcher** con il proprio **Client BitTorrent** e **autogestore di repack**.
> e **autogestore di repack**

this part was not in the original readme, please keep only what already exists

2024-11-27 03:51 UTC, Hachi-R commented on README.it.md
> +- Motore di ricerca automatizzato sulle fonti di repack dal [Megathread]("https://www.reddit.com/r/Piracy/wiki/megathread/")
this part was not in the original readme, please keep only what already exists

**do not use external and piracy related links**

2024-11-27 03:51 UTC, Hachi-R commented on README.it.md
> +- Notifiche di aggiornamenti sulla list dei repacks
remove this line

2024-11-27 03:51 UTC, Hachi-R commented on README.it.md
> +
wtf is this environment variables?

please only consider the main [README](https://github.com/hydralauncher/hydra/blob/main/README.md).

2025-01-05 10:41 UTC, thegrannychaseroperation commented
Thanks for your contribution.

Please move any documentation translation to this new repo: https://github.com/hydralauncher/hydra-docs
That would be much appreciated! Thank you in advance.

2025-01-05 10:41 UTC, closed without merging