Add modal to confirm if user really wants to delete game archives
hydralauncher/hydra pull request #13
Opened 2024-04-14 14:15 UTC by xbozo

Preview:
![Screenshot_2](https://github.com/hydralauncher/hydra/assets/119091492/39292ed3-8a8e-4fec-bc52-0e7e271bcd5f)

2024-04-14 14:22 UTC, xbozo commented
![Screenshot_2](https://github.com/hydralauncher/hydra/assets/119091492/0c474b63-3e00-4e79-9088-c77a03a8eae8)

2024-04-15 18:30 UTC, hydralauncher requested changes

2024-04-15 18:30 UTC, hydralauncher commented on src/renderer/pages/game-details/delete-modal.tsx
> +type DeleteModalProps = {
Please use `interface` instead

2024-04-15 18:30 UTC, hydralauncher commented on src/renderer/pages/game-details/delete-modal.tsx
> +  title: string;
Why do you have to pass `title` and `description` as props if they're always the same and this component is going to be used in a single place?

2024-04-15 18:30 UTC, hydralauncher commented on src/renderer/pages/game-details/delete-modal.tsx
> +          onClick={() => {
Don't create a new function if not necessary, use `onClick={onClose}` instead

2024-04-15 18:30 UTC, hydralauncher commented on src/renderer/pages/game-details/delete-modal.tsx
> +          onClick={() => {
Move this to a separate function

2024-04-15 18:43 UTC, xbozo commented
fix @hydralauncher

2024-04-15 18:43 UTC, hydralauncher commented on src/renderer/pages/game-details/delete-modal.tsx
> +  function handleDeleteGame() {
Use arrow functions within the component context

2024-04-15 18:45 UTC, hydralauncher commented
LGTM

2024-04-15 18:46 UTC, merged