Fixed it so Ka0s repacks work on linux
hydralauncher/hydra pull request #153
Opened 2024-05-01 18:58 UTC by gylli251

Fixed it so Ka0s repacks work on linux, its using Setup.exe instead of setup.exe.

Side-note:

Should i implement it so if nether setup.exe or Setup.exe is found it prompts the user to select the installer executable?

2024-05-01 19:09 UTC, gylli251 commented
found a bug with the yaml generating. fixing it then commiting

2024-05-01 19:10 UTC, lilezek approved these changes

2024-05-01 19:12 UTC, Magrid0 approved these changes
Looks good to me, thanks for your contribution

2024-05-01 19:37 UTC, lilezek approved these changes

2024-05-01 19:37 UTC, lilezek commented on src/main/events/library/open-game-installer.ts
> +  const files = fs.readdirSync(gamePath);
Maybe it makes sense to turn this into a helper function at this point. Any hardcoded names would work fine in windows but may break in linux if name changes capitalization.

2024-05-01 20:58 UTC, gylli251 commented
Turns out Kaos repacks installer does not work at all on Linux, i reached out to them to try to get a resolution to get it working with hydra.

2024-05-02 08:24 UTC, hydralauncher requested changes
A few tweaks here and there, looks good overall

2024-05-02 08:24 UTC, hydralauncher commented on src/main/events/helpers/generate-lutris-yaml.ts
> +  const files = fs.readdirSync(gamePath);
Please don't use synchronous operations when using I/O since this might potentially lock the main thread

2024-05-02 08:24 UTC, hydralauncher commented on src/main/events/helpers/generate-lutris-yaml.ts
> +};
No newline

2024-05-02 08:24 UTC, hydralauncher commented on src/main/events/library/open-game-installer.ts
> +  if (!setupPath || !fs.existsSync(setupPath)) {
Don't use synchronous I/O operations

2024-05-23 19:11 UTC, thegrannychaseroperation commented
Closing this since I haven't had any updates in a while.

2024-05-23 19:11 UTC, closed without merging