Added screenshots and trailers to game details
hydralauncher/hydra pull request #200
Opened 2024-05-05 02:48 UTC by Mkdantas

Added a slider with videos and screenshots of the game in game details.

This PR resolves #158

2024-05-05 02:56 UTC, zamitto commented on .env.example
Please, reverse the exclusion of this file

2024-05-05 02:57 UTC, zamitto commented on src/renderer/src/pages/game-details/gallery-slider.tsx
please, format this file with prettier

2024-05-05 02:58 UTC, zamitto commented on src/renderer/src/pages/game-details/game-details.tsx
> +  console.log(gameDetails)
please, remove this console log

2024-05-05 02:59 UTC, zamitto commented
I added some comments after a *quick* check

2024-05-05 03:10 UTC, Mkdantas commented
> I added some comments after a **quick** check

Thank you, will resolve this issues and let you know when is ready

2024-05-05 03:26 UTC, zamitto commented
also, the screenshots seems too big, maybe send in the discord channel how it is now so other people say what they think

2024-05-05 03:28 UTC, Mkdantas commented
> I added some comments after a **quick** check

Done, thank you for the rapid feedback. Let me know if you have more.

Let me know if the screenshots and videos slider is placed in the desired locaiton or if i should move it to the bottom of details page.

Also, i realized that the description does not have a title indicating where it starts, so if you want i can remove the title i created for the slider section

2024-05-05 03:50 UTC, hydralauncher requested changes

2024-05-05 03:50 UTC, hydralauncher commented on .env.example
> -RENDERER_VITE_SENTRY_DSN=YOUR_SENTRY_DSN
Please remove your change from this file

2024-05-07 04:55 UTC, hydralauncher approved these changes
LGTM

2024-05-07 04:55 UTC, merged