feat/add context menu
hydralauncher/hydra pull request #236
Opened 2024-05-08 03:18 UTC by xbozo

![image](https://github.com/hydralauncher/hydra/assets/119091492/8174b9c5-89dd-4eb6-908d-8bb04f662267)

1. Open archive location --> if user has already selected an exe it opens the folder based on this exe location. If not, it opens the installation folder path.
2. Change executable path --> Self-explained.
3. Remove installation archives --> Deletes installation folder; the one located on the download path. Keeps other files (such as the folder where the selected exe with the installed game is) intact. Helpful to get rid of unused archives and free disk space.

solve #220 
solve #130 
solve #118 
solve #71

2024-05-09 17:05 UTC, lilezek requested changes

2024-05-09 17:05 UTC, lilezek commented on src/renderer/src/components/sidebar/sidebar.tsx
> +            <div className={styles.menu}>
Do not change a `<ul>` into a `<div>`. This element includes `<li>` elements.

2024-05-09 17:05 UTC, lilezek commented on src/renderer/src/hooks/use-download.ts
> +      .catch(() => {})
Is this catch needed? Should it at least log the error?

2024-05-09 17:05 UTC, lilezek commented on src/renderer/src/pages/game-details/hero/hero-panel-actions.tsx
> +    await updateLibrary();
Why is updating the library needed before opening a game?

2024-05-09 17:09 UTC, xbozo commented on src/renderer/src/components/sidebar/sidebar.tsx
> +  const [axilCoordinates, setAxilCoordinates] = useState({
yes, wrong spelling*

2024-05-09 17:12 UTC, xbozo commented on src/renderer/src/components/sidebar/sidebar.tsx
> +          name: "Game executable",
wdym?

2024-05-09 17:29 UTC, xbozo commented
adjusted

2024-05-09 18:14 UTC, xbozo commented
> > adjusted
> 
> Everything looks good but the transformation from `<ul>` to `<div>`. Can you leave it to be an `<ul>` as it was originally?
> 
> Also, I'm still wondering why is updating the library needed before opening a game. I'm not saying it is wrong, but I don't get it. Could you elaborate?

debugging reasons.
changed already

2024-05-09 18:25 UTC, lilezek commented
LGTM

2024-05-27 20:31 UTC, zamitto commented on src/main/entity/game.entity.ts
No need to have changes on this file. Keep as little changes as possible, please

2024-05-27 20:39 UTC, zamitto commented on src/main/events/misc/show-open-dialog.ts
No need to have changes on this file. Keep as little changes as possible, please.

And AFAIK, the function used in the event needs to be asyn

2024-05-27 20:39 UTC, zamitto commented on src/main/events/library/open-game.ts
No need to have changes on this file. Keep as little changes as possible, please

2024-05-27 20:40 UTC, zamitto commented on src/renderer/src/assets/discord-icon.svg
Discord icon is not used anymore

2024-05-27 20:42 UTC, zamitto commented on src/main/events/library/delete-game-folder.ts
No need to have changes on this file. Keep as little changes as possible, please.

2024-05-27 20:44 UTC, zamitto commented
Are you using Prettier with the project settings? A few changes seems that would be fixed by prettier. And overall, try to make as little changes as possible. I made just a quick review

2024-05-28 15:11 UTC, xbozo commented on src/renderer/src/assets/discord-icon.svg
should sub for telegram?

2024-05-28 15:55 UTC, xbozo commented
adjusted

2024-06-23 23:12 UTC, closed without merging